### ISSUE TITLE
Data loading

### ISSUE THREAD

**Issue by martinrisseeuw** [cambecc/air#5]
Hi Cambecc,

I am trying to setup a version of the Tokyo Wind Map on my machine. I have followed the steps in the description unfortunately I can't get it running properly. When I start the server I get the error 500 Internal Server Error. 

When I look at the console, it gives an error: 
"NetworkError: 500 Internal Server Error - http://localhost:8080/data/wind/current"

I started the server using this command: 
node server.js 8080 postgres://postgres:12345@localhost:5432/air http://www.taiki.kankyo.metro.tokyo.jp

It does give back some errors:

```
2015-06-03T08:48:26.369Z - error: error: password authentication failed for user "postgres"
    at Connection.parseE (/Users/martinrisseeuw/Dropbox/Development projects/Windmap/node_modules/pg/lib/connection.js:526:11)
    at Connection.parseMessage (/Users/martinrisseeuw/Dropbox/Development projects/Windmap/node_modules/pg/lib/connection.js:371:17)
    at Socket.<anonymous> (/Users/martinrisseeuw/Dropbox/Development projects/Windmap/node_modules/pg/lib/connection.js:86:20)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
2015-06-03T08:48:26.370Z - info: 127.0.0.1 - - GET /data/wind/current HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0" http://localhost:8080/ - gzip, deflate
```

I hope you can help me. I would like to use your project as a starting point for displaying flow and water quality. 

Best,

Martin

**Comment by evz** [comment]
Ran into the same thing. You need to put in the actual credentials you use to get into your postgresql database. So, instead of `postgres` and `12345` you need to put in the actual user and password.
