### ISSUE TITLE
error: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by guazipi** [cambecc/air#6]
# HI，very appreciate it that you develop this project, and I am trying to build a version of the Tokyo Wind Map on my machine. I have followed the steps in the readme.md, unfortunately some errors come up, could you help me to solve this problem. Here is the error.

2015-11-08T06:53:36.783Z - Starting
2015-11-08T06:53:37.397Z - info: Listening on port 8030...
2015-11-08T06:53:37.419Z - info: Preparing tables...
2015-11-08T06:53:37.423Z - info: Persisting...
2015-11-08T06:53:37.493Z - info: get: www.taiki.kankyo.metro.tokyo.jp/cgi-bin/bunpu1/p160.cgi?no2===1==2====2=
2015-11-08T06:53:37.499Z - info: get: www.taiki.kankyo.metro.tokyo.jp/cgi-bin/bunpu1/p160.cgi?no2===2==2====2=
2015-11-08T06:53:37.516Z - error: Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1010:19)
Potentially unhandled rejection [2] Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1010:19)
Thanks a lot!

**Comment by guazipi** [comment]
I've solved this problem, It's stupid, but thanks all the same!

**Comment by vlasvlasvlas** [comment]
hi! what was the issue? having the same here :P thanks

`
at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
`
