### ISSUE TITLE
local version, non-tokyo topojson, local data

### ISSUE THREAD

**Issue by vlasvlasvlas** [cambecc/air#8]
Hi, i was testing the project to load a local topojson of another country, anoter points ot stations and local meteorology data.

This is what a did:
- i truncated and inserted local stations data, stations with local geom x,y, 
- i truncated and inserted local meteo data at samples referencing station id,
- i changed the public/data/tokyo-topo.json with my own tokyo-topo.json (same name, different geometry)

but i got this error:

```
nodejs server.js 8080 postgres://postgres:postgres@localhost/air
============================================================
2016-09-27T21:38:52.052Z - Starting
2016-09-27T21:38:52.226Z - info: Listening on port 8080...

module.js:485
    throw err;
          ^
SyntaxError: /opt/air/station-data.json: Unexpected number
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/air/server.js:21:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

my /opt/air/station-data.json: 

```
[
        [1, "1", "1", -54.750000, -67.750000],
        [2, "2, "2", -54.750000, -67.750000],
        [3, "3", "3", -54.750000, -67.250000],
        [4, "4", "4",  -54.750000, -66.750000],
        [5, "5", "5", -54.750000, -66.250000],
        [6, "6", "6", -54.750000, -65.750000],
        [7, "7", "7", -54.750000, -65.250000],
        [8, "8", "8", -54.750000, -64.250000],
        [9, "9", "9", -54.250000, -68.250000],
        [10, "10", "10", -54.250000, -67.750000],
        [11, "11", "11", -54.250000, -67.250000]
]
```

topojson:
https://github.com/vlasvlasvlas/topojsons/blob/master/map-argentina.topojson

what could this be?

**Comment by moran-xu** [comment]
Have you got an idea as what was going on? I meet the same problem as you. ><
